### ISSUE TITLE
minor color issue with stacktrace

### ISSUE THREAD

**Issue by hannesdelbeke** [martinlanton/maya_script_editor_highlighter#3]
i noticed stack traces don't handle color correctly

i'd expect the yellow arrows to also be blue, but only the stacktrace line is recognised currently
![image](https://github.com/martinlanton/maya_script_editor_highlighter/assets/3758308/afb7c86b-1da9-4adc-bbb3-05b0aa6397b8)

priority: it's a minor issue

**Comment by martinlanton** [comment]
Thanks!
Sorry I didn't see this issue until just now, that said I just pushed a change that I believe should take care of this properly now.

Let me know if that works on your end, so I can close the issue.

**Comment by hannesdelbeke** [comment]
yep , just tested that 1 line
![image](https://github.com/martinlanton/maya_script_editor_highlighter/assets/3758308/836b85ef-12f2-481f-9b5b-560427d0b411)

**Comment by hannesdelbeke** [comment]
i still have these issues sometimes
where stack trace is not coloring 

![image](https://github.com/martinlanton/maya_script_editor_highlighter/assets/3758308/eb16df82-5519-4d03-8096-05d5af96520d)

**Comment by martinlanton** [comment]
> i still have these issues sometimes where stack trace is not coloring
> 
> ![image](https://private-user-images.githubusercontent.com/3758308/325897383-eb16df82-5519-4d03-8096-05d5af96520d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQxNTI3MjgsIm5iZiI6MTcxNDE1MjQyOCwicGF0aCI6Ii8zNzU4MzA4LzMyNTg5NzM4My1lYjE2ZGY4Mi01NTE5LTRkMDMtODA5Ni0wNWQ1YWY5NjUyMGQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDQyNiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA0MjZUMTcyNzA4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9YmZhOWU1ZjdjMmUyZWE0ZTM2YjljYmNhNzU0MWViMjFlMGU4NmVhNjE1MTA4MmQ0NzAxMDhhNTllN2EyNjFlOCZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.95l5mV_dCk0OQHxPf8Wmf4ZaV_7V0R-hk-diOT1ngk4)

I believe that would be due to the regex not detecting it properly, I'll have to make it a little more complex. Can you add the full stack trace as a code block? That would help.

Additionally when that happens in the future, I think it'd make more sense to create a new issue each time as each of them will probably require an update of the regex to detect this.

**Comment by hannesdelbeke** [comment]
will do next time. I don't have the original traceback but will add when i see it

**Comment by martinlanton** [comment]
I just pushed a new change that should address this problem @hannesdelbeke 

If the problem is still present after this update, then I will need a snippet of code to reproduce the error in question. Feel free to open a new issue with the code snippet to reproduce the problem if that is the case.
